import React from "react"
import Button from "./button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/xf57kACm2E1z20Fx3KHsFe?node-id=2%3A3",
  {
    props: {},
    example: (props) => <Button />,
  },
)
